# Custom Command Toggle 
# Exported settings for the Custom Command Toggle extension 
# File generated on 03/10/2026, 18:53:18 
# 
# --- Settings Information ---
# button-name: <text> 
# icon: <text> 
# toggle-on-command: <command> 
# toggle-off-command: <command> 
# check-status-command: <command> 
# search-term: <text> 
# initial-state: 0, 1, 2, or 3 
#     0 = On 
#     1 = Off 
#     2 = Previous state 
#     3 = Command output 
# run-at-startup: true or false 
# startup-delay-time: 0-10 (seconds) 
# check-status-delay-time: 0-10 (seconds) 
# button-click-action: 0, 1, or 2 
#     0 = Always on 
#     1 = Always off 
#     2 = Toggle 
# check-exit-code: true or false 
# show-indicator: true or false 
# close-menu: true or false 
# command-sync: true or false 
# polling-frequency: 2-900 (seconds) 
# keyboard-shortcut: <shortcut> 
# enabled: true or false 
# 
#
[Toggle 1]
button-name=GPU Game Mode
icon=speedometer-symbolic
toggle-on-command=bash -c 'DEV="/sys/class/drm/card1/device"; ID=$(awk "/COMPUTE/ {gsub(\\":\\", \\"\\", \\$1); print \\$1; exit}" "$DEV/pp_power_profile_mode"); echo manual | sudo tee "$DEV/power_dpm_force_performance_level" > /dev/null && echo "$ID" | sudo tee "$DEV/pp_power_profile_mode" > /dev/null'
toggle-off-command=bash -c 'DEV="/sys/class/drm/card1/device"; ID=$(awk "/POWER_SAVING/ {gsub(\\":\\", \\"\\", \\$1); print \\$1; exit}" "$DEV/pp_power_profile_mode"); echo manual | sudo tee "$DEV/power_dpm_force_performance_level" > /dev/null && echo "$ID" | sudo tee "$DEV/pp_power_profile_mode" > /dev/null'
check-status-command=
search-term=
initial-state=1
run-at-startup=true
startup-delay-time=3
check-status-delay-time=3
button-click-action=2
check-exit-code=false
show-indicator=true
close-menu=false
command-sync=false
polling-frequency=10
keyboard-shortcut=
enabled=true
